version: '3.3'

services:
  note-app:
    build: ./
    command: ./wait-for-postgres.sh db ./note-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - DB_PASSWORD=qwerty
      - KEY_SALT=sdlkfgjhlkjh34lser34523cfrv
      - KEY_SIGNINGKEY=dklfgjh34lkrnmlvmwe

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"