version: '3.5'

services:
  note-app:
    build: ./
    command: ./wait-for-postgres.sh db ./note-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rdb
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - DB_PASSWORD=qwerty
      - RDB_HOST=rdb
      - RDB_PORT=6379
      - KEY_SALT=sdlkfgjhlkjh34lser34523cfrv
      - GRPC_HOST=noteslog
      - GRPC_PORT=9000
    networks:
      - app

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"
    networks:
      - app

  rdb:
    restart: always
    image: redis:latest
    volumes:
      - /myredis/conf:/usr/local/etc/redis
    ports:
      - "6379:6379"
    networks:
      - app

networks:
  app:
    name: note_network
